### ISSUE TITLE
Dataform encountered an error: Could not find a recent installed version of @dataform/core in the project. Ensure packages are installed and upgrade to a recent version.

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-dataform#3]
### Feature description

Reproducer:

```yaml
id: dataform_plugin
namespace: qa

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: https://github.com/dataform-co/dataform-example-project-bigquery                

      - id: transform
        type: io.kestra.plugin.dataform.cli.DataformCLI
        beforeCommands:
          - dataform compile
        commands:
          - dataform run --dry-run
```

We need to find a proper way to install dataform core.

![image](https://github.com/kestra-io/plugin-dataform/assets/86264395/0ff75f28-147a-4dc6-8062-fe2be3024745)

**Comment by anna-geller** [comment]
there's no need to cd into the project directory, the git clone task already does it

the problem here are only dataform core dependencies 

![image](https://github.com/kestra-io/plugin-dataform/assets/86264395/a158ccb6-f9b6-4283-a7ff-52dcee6c310b)

**Comment by anna-geller** [comment]
very old issue, I'll assume that the more recent example from docs will work. if someone sees otherwise, we'd appreciate a bug report:

```yaml
id: dataform
namespace: company.team
tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: https://github.com/dataform-co/dataform-example-project-bigquery

      - id: transform
        type: io.kestra.plugin.dataform.cli.DataformCLI
        beforeCommands:
          - npm install @dataform/core
          - dataform compile
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "sa.json"
        inputFiles:
          sa.json: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
          .df-credentials.json: |
            {
              "projectId": "<gcp-project-id>",
              "location": "us"
            }
        commands:
          - dataform run --dry-run
```
